version: '3.8'

services:

  #  [  Back  ]  # 
  web_server:
    container_name: back_server
    build: ./backend/node_api/
    env_file: .env
    # volumes:
    # - ./backend/php/:/var/www/html/
    ports:
      - ${SERVER_PORT}:3000
    networks:
      - camagru_back_network
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mongo_db
    image: mongo:8.0
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      # - ./backend/mongodb/volume:/data/db
      - mongo-data:/data/db
    # - ./backend/db_volume/:/var/lib/mysql/
    # - ./backend/mysql/:/docker-entrypoint-initdb.d
    networks:
      - camagru_back_network
    restart: always

    #  [  Front  ]  # 
  front:
    container_name: front-next.js
    build: ./frontend/
    env_file: .env
    ports:
      - ${FRONT_PORT}:3000
    restart: always
    depends_on:
      - web_server
    volumes:
      # Volume pour le DEV permetant rebuild en temps reel
      - ./frontend/front-react:/app
      # Assure l'utilisation des modules installes dans le container
      - /app/node_modules

networks:
  camagru_back_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
