version: '3.8'

services:

  #  [  Back  ]  # 
  web_server:
    container_name: back_server
    build: ./backend/node_api/
    env_file: .env
    # volumes:
    # - ./backend/php/:/var/www/html/
    ports:
      - ${SERVER_PORT}:3000
    networks:
      - camagru_back_network
    restart: unless-stopped
    # [ Condition du HealthCheck ! ]
    depends_on:
      mongo:
        conndition: service_healthy



  mongo:
    container_name: mongo_db
    image: mongo:8.0
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      # - ./backend/mongodb/volume:/data/db
      - mongo-data:/data/db
    # - ./backend/db_volume/:/var/lib/mysql/
    # - ./backend/mysql/:/docker-entrypoint-initdb.d
    # environment:
    #   - MYSQL_ROOT_PASSWORD=MonRootyPass
    #   - MYSQL_DATABASE=camagru_db
    #   - MYSQL_USER=serviceMan
    #   - MYSQL_PASSWORD=psw
    networks:
      - camagru_back_network
    # [ ping 5 fois la db a interval de 5 secondes pour check quelle est bien up ! ]
    healthcheck:
      test: ["CDM-SHELL", "pg_isready -p ${MONGO_PORT} -U ${MONGO_USER} -d ${MONGO_DB}"]
      interval: 5s
      timeout: 5s
      retry: 5



    #  [  Front  ]  # 
  front:
    container_name: front-next.js
    build: ./frontend/
    env_file: .env
    ports:
      - ${FRONT_PORT}:3000
    restart: unless-stopped
    depends_on:
      - web_server
    volumes:
      # Volume pour le DEV permetant rebuild en temps reel
      - ./frontend/front-react:/app
      # Assure l'utilisation des modules installes dans le container
      - /app/node_modules

networks:
  camagru_back_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
